title = "inTUItive theme"
theme = "hugo-in-tui-tive"
themesDir = "../.."
enableRobotsTXT = true
hasCJKLanguage = true
baseURL = ""

[pagination]
pagerSize = 6

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4

[params]
mainSections = ['posts']

## uncomment belows and set proper values to enable remark42
# [params.remark42]
# host=''
# site_id=''
# max_shown_comments=100
# theme='light'
# locale='en'
# show_email_subscription=false
# simple_view=true


# To set multiple footer rows, set up each row like so:
# [[params.footer_rows]]
# name/url/pre = "contents"
#
# The `pre` block lets you define your own format for the footer row entirely,
# used here to insert icons from FontAwesome.

[[params.footer_rows]]
name = "Creative Commons Attribution 4.0 International"
url = "https://creativecommons.org/licenses/by/4.0/"
pre = "Copyright <a href='https://creativecommons.org/licenses/by/4.0/'><i class='fa-brands fa-creative-commons'></i>&nbsp;<i class='fa-brands fa-creative-commons-by'></i>&nbsp;CC BY-4.0</a>"

[[params.footer_rows]]
name = "Hugo"
url = "https://gohugo.io"
pre = "Powered by <a href='https://gohugo.io'><i class='fa-solid fa-rocket'></i>&nbsp;Hugo</a>"

[[params.footer_rows]]
name = "inTUItive theme"
url = "https://github.com/ben-zen/hugo-in-tui-tive/"
pre = "Theme <a href='https://github.com/ben-zen/hugo-in-tui-tive/'><i class='fa-brands fa-square-github'></i>&nbsp;ben-zen/hugo-in-tui-tive</a>"


[[menus.main]]
name = "Posts"
url = "/posts/"
weight = 30

[[menus.main]]
name = "Essays"
url = "/essays/"
weight = 40

[[menus.main]]
pageref = "about"
name = "About"
weight = 80

# 2-level sub menus are supported
[[menus.main]]
name = "Services"
weight = 60
[[menus.main]]
parent = "Services"
name = "Service A"
url = "#"
[[menus.main]]
parent = "Services"
name = "Service B"
url = "#"
